# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJ2w2G9vpqOdOnRb1EmthpvyMwU6PaOb
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load(open('model_obesitas_optimal.pkl', 'rb'))

st.title('Capstone Project Lu')

# Input dari user
input1 = st.number_input("Masukkan nilai 1:")
input2 = st.number_input("Masukkan nilai 2:")

# Prediksi
if st.button("Prediksi"):
    pred = model.predict([[input1, input2]])
    st.success(f"Hasil prediksi: {pred[0]}")